version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: virtuwear
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cucuklauk123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - virtu-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtu_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/virtuwear
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cucuklauk123
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - virtu-network

volumes:
  pgdata:

networks:
  virtu-network:
